version: 2.1
orbs:
  azure-cli: circleci/azure-cli@1.2.1
jobs:
  build:
    description: Setup laravel application and run tests
    docker:
      # Specify the version you desire here
      - image: cimg/php:8.0-browsers

    steps:
      - checkout

      - run:
          name: "Prepare environment"
          command: |
            sudo apt update
      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: "Install dependencies"
          command: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run:
          name: "Create .env file and generate app key"
          command: |
            mv .env.example .env
            php artisan key:generate
            ls

      - run:
          name: "Run tests"
          command: php vendor/bin/phpunit
      - persist_to_workspace:
          root: ~/project
          paths:
            - app

  login-to-azure-and-deploy:
    executor: azure-cli/default
    steps:
      - azure-cli/install
      - azure-cli/login-with-user:
          alternate-tenant: false
      - attach_workspace:
          at: ~/project
      - run:
          command: az webapp deployment source show --resource-group demoApp --name laravel-api
      - run:
          name: "Deploy Web App to Azure"
          command: |
            az webapp deployment source config-local-git --resource-group demoApp --name laravel-api
            cd ~/project/
            ls
            git init
            git config --global user.email "me@mail.com"
            git config --global user.name "yemiwebby"
            git add .
            git commit -m "project update"
            git remote add azure https://$GIT_USERNAME:$GIT_PASSWORD@laravel-api.scm.azurewebsites.net/laravel-api.git
            git push azure master --force
workflows:
  build-and-deploy:
    jobs:
      - build
      - login-to-azure-and-deploy:
          requires:
            - build
